/**
 * Type Guards Module
 * Single Responsibility: Runtime type checking
 *
 * Uses factory functions to eliminate code duplication
 */

import { DifficultyLevel, SectionType } from '../types/enums';
import {
  Section,
  ChapterSection,
  TitleSection,
  GlossarySection,
  BibliographySection,
  ContentSection,
  ArticleData
} from '../types/interfaces';

// ============================================================================
// FACTORY FUNCTIONS (DRY Principle)
// ============================================================================

/**
 * Generic enum validator factory
 * Eliminates code duplication for enum type guards
 */
function createEnumValidator<T extends Record<string, string>>(enumObj: T) {
  return (value: unknown): value is T[keyof T] => {
    return typeof value === 'string' && Object.values(enumObj).includes(value as T[keyof T]);
  };
}

/**
 * Generic section type guard factory
 * Eliminates code duplication for section type checks
 */
function createSectionTypeGuard<T extends Section>(
  sectionType: SectionType
): (section: Section) => section is T {
  return (section: Section): section is T => section.type === sectionType;
}

// ============================================================================
// ENUM TYPE GUARDS (Generated by Factory)
// ============================================================================

export const isDifficultyLevel = createEnumValidator(DifficultyLevel);
export const isSectionType = createEnumValidator(SectionType);

// ============================================================================
// SECTION TYPE GUARDS (Generated by Factory)
// ============================================================================

export const isChapterSection = createSectionTypeGuard<ChapterSection>(SectionType.CHAPTER);
export const isTitleSection = createSectionTypeGuard<TitleSection>(SectionType.TITLE);
export const isGlossarySection = createSectionTypeGuard<GlossarySection>(SectionType.GLOSSARY);
export const isBibliographySection = createSectionTypeGuard<BibliographySection>(SectionType.BIBLIOGRAPHY);

// ============================================================================
// SPECIALIZED TYPE GUARDS
// ============================================================================

/**
 * Type guard to check if section has difficulty
 */
export function hasDifficulty(section: Section): section is ContentSection | ChapterSection {
  return 'difficulty' in section && section.difficulty !== undefined;
}

/**
 * Type guard to check if a section is valid
 */
export function isValidSection(value: unknown): value is Section {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const section = value as Partial<Section>;

  return (
    typeof section.id === 'string' &&
    typeof section.title === 'string' &&
    (section.content === undefined || typeof section.content === 'string') &&
    (section.type === undefined || isSectionType(section.type)) &&
    (section.difficulty === undefined || section.difficulty === null || isDifficultyLevel(section.difficulty))
  );
}

/**
 * Type guard to check if article data is valid
 */
export function isValidArticleData(value: unknown): value is ArticleData {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const data = value as Partial<ArticleData>;

  return (
    typeof data.title === 'string' &&
    Array.isArray(data.sections) &&
    data.sections.every(isValidSection) &&
    (data.subtitle === undefined || typeof data.subtitle === 'string') &&
    (data.version === undefined || typeof data.version === 'string')
  );
}
